### ISSUE TITLE
How do you install this?

### ISSUE THREAD

**Issue by KrishaanKhubchand** [i3arnon/YouCast#10]
So yeah, I'm kinda clueless as to how I can install/compile the code? Could someone tell me what to do?

**Comment by i3arnon** [comment]
You don't need to compile anything in order to install YouCast.
You can download it directly from the latest release: https://github.com/i3arnon/YouCast/releases
Or you can visit the landing site and click the Download button: http://youcast.i3arnon.com/

**Comment by KrishaanKhubchand** [comment]
Thank you!
