### ISSUE TITLE
Podcast managers reject the link generated for playlists

### ISSUE THREAD

**Issue by cblupodev** [i3arnon/YouCast#12]
The Apple podcast player [[goo.gl]](https://goo.gl/photos/oRSVJdFRqVVsSoSu5) and Overcast [[goo.gl]](https://goo.gl/photos/5yAURWzcgiDENoqC7) reject the link generated for playlists. The generated link was http://192.168.1.219:22703/FeedService/GetUserFeed?userId=PLsjYkd6fRiB6ay7ycFVZ6VNiyrwgdFiu-&encoding=MP4_720p&maxLength=10&isPopular=False. This is the playlist I'm using as an example, it's public [[All Sports. One video, each sport - youtube.com]](https://www.youtube.com/playlist?list=PLsjYkd6fRiB6ay7ycFVZ6VNiyrwgdFiu-). However, all other playlists I've tried don't work either

Creating podcasts for channel uploads works fine; it's only playlists with the problem

**Comment by i3arnon** [comment]
Hey, your link doesn't seem like a playlist link (it calls `GetUserFeed`). You need to use the dropdown menu to choose playlist first and then generate your link:

![image](https://cloud.githubusercontent.com/assets/6595156/16361236/cfd0609a-3b91-11e6-857d-c96011e6a03d.png)

**Comment by cblupodev** [comment]
Awesome! Thank you
