### ISSUE TITLE
M4A feed - 128kbps : OK / 192kbps : Error

### ISSUE THREAD

**Issue by HanaBookStory** [i3arnon/YouCast#13]
Great Thanks to i3aron.
YOUCAST is Great Application for me.
......

Some Video has Error on M4A feed.

See this Link.
https://goo.gl/6SDbDo
(This capture is windows explorer screen capture about downloaded youtube MP4 and M4a files.)

[LIST]
- Video ID - File Name - Audio Bitrate - M4a Feed OK 
- y-49TXhDFmQ - A01.mp4 - 125kbps - O
- xWNx0jgbKoM - A02.mp4 - 192kbps - X
- gCH70s0hXGw - A03.mp4 - 191kbps - X
- SY5cGxG0qnk - A04.mp4 - 125kbps - O
- ME8pdL6mi5g - A05.mp4 - 125kbps - O
- DWYI6K5Hkog - A06.mp4 - 125kbps - O
- P-J_Qc3pzbQ - A07.mp4 - 125kbps - O
- 5A73ZpjFhik - A08.mp4 - 191kbps - X
- MVpTpPh-uDo - A09.mp4 - 125kbps - O
- oVgiA0XgrYg - A10.mp4 - 125kbps - O
- 44r7a-oziQc - B01.mp4 - 192kbps - X
- b6TZRywav_M - B02.mp4 - 191kbps - X
- drJYN88q4uk - B03.mp4 - 125kbps - O
- bCv1tmlZfRE - B04.mp4 - 125kbps - O
- MLrJquCv4To - B05.mp4 - 125kbps - O

[FEED]
A01 : OK
youcast.cloudapp.net/FeedService/Audio.m4a?videoId=y-49TXhDFmQ

A02 : Error
youcast.cloudapp.net/FeedService/Audio.m4a?videoId=xWNx0jgbKoM
.
.
.

- MP4 with 128kbps audio : M4A Feed is OK.
- MP4 with 192kbps audio : M4A Feed has Error.

I think there are some differeces between 128kbps and 192kbps..

...

anyway, Thanks about this application.
Best regards..

**Comment by i3arnon** [comment]
@HanaBookStory 

I think I found the problem using your examples. I'm not sure it relates to the audio quality but YouTube returns the urls in a different format that doesn't work.

I've sent a pull request fixing this issue (I think) to libvideo which is the library I use to get YouTube download urls. When (and if) the owner will accept the fix I'll update YouCast to reflect that.
You can follow the discussion here: https://github.com/jamesqo/libvideo/pull/57

Thank you for raising this issue.

**Comment by i3arnon** [comment]
@HanaBookStory Instead of waiting for the changes to be accepted to the main library I pushed my version to the cloud service. Please verify that my changes fix your issue.

**Comment by HanaBookStory** [comment]
Thank You, Arnon! Everything is OK!
