### ISSUE TITLE
Mac Port

### ISSUE THREAD

**Issue by PandaKemper** [i3arnon/YouCast#14]
How difficult would it be to create a mac version for OSX in the form of a .dmg? Thanks!

**Comment by i3arnon** [comment]
It depends on whether it uses the cloud service or not.
If it does, then it's pretty simple as all that's needed is to generate the urls in the right way and they'll point to the cloud service.
If it doesn't, and the app needs to contain the actual service that queries YouTube then it's somewhat difficult. It would basically be writing the entire app from scratch.
