### ISSUE TITLE
v2.2 hangs at UAC

### ISSUE THREAD

**Issue by oolyum** [i3arnon/YouCast#15]
Wanted to try the new version, but it just hangs when I try to run it, even as Administrator.  Doesn't seem to want to trigger the UAC.  I tried turning off UAC, but it still won't load.  Any ideas?

**Comment by i3arnon** [comment]
Do you maybe have another instance of YouCast already open? In that case the new instance will try to communicate with the existing one and bring it to focus. Maybe that fails...

**Comment by oolyum** [comment]
Nope.  To be sure, I rebooted the machine, and tried to launch v2.2.  Same issue, it just hangs and doesn't trigger UAC.  :(

**Comment by oolyum** [comment]
Update:  Turns out it was a bug in last release of Win10.  It caused the UAC to open behind Explorer.  Latest update fixed the issue.  I'm using v2.2 now, and the cloud function is pretty sweet.  Great job.

**Comment by i3arnon** [comment]
Great, because I had no idea how to fix this issue.
I'm glad this sorted itself out.
