### ISSUE TITLE
Links with access denied

### ISSUE THREAD

**Issue by theagoliveira** [i3arnon/YouCast#16]
I created an [audio feed](http://youcast.cloudapp.net/FeedService/GetUserFeed?userId=UCktZ9zQ_t3-Id0aKjJvRSxA&encoding=Audio&maxLength=0&isPopular=False) for [this channel](https://www.youtube.com/channel/UCktZ9zQ_t3-Id0aKjJvRSxA) and subscribed using _Pocket Casts_ app. For some reason, the app cannot download some links (videos with length greater than 40 minutes), because it is forbidden. For example:

```
<item>
<guid isPermaLink="false">374SgPGPtjo</guid>
<link>http://www.youtube.com/watch?v=374SgPGPtjo</link>
<title>Decrépitos AO VIVO - Vortando das Férias</title>
<description>
Bom memento, país muito louco da América do Sul (Brasil). No ar mais um AO VIVO do popcast mais coisado da podosfera brasileira!! Pra participar pelo Twitter basta usar a hash hash #VivaldãoDaMassa http://decrepitos.com Montagem por @Yanyys_ - http://twitter.com/Yanyys_
</description>
<pubDate>Sat, 21 Jan 2017 00:38:41 Z</pubDate>
<a10:content type="text"/>
<enclosure type="audio/mp4" url="http://youcast.cloudapp.net:80/FeedService/Audio.m4a?videoId=374SgPGPtjo"/>
</item>
```
I tried to access `http://youcast.cloudapp.net:80/FeedService/Audio.m4a?videoId=374SgPGPtjo` using Chrome and it says 

> You don't have authorization to view this page.

>

**Comment by i3arnon** [comment]
I did manage to download this specific audio file. Maybe you can too now?
The audio feed (and all YouCast) is basically a "best effort". It works when it works and when YouTube blocks it there isn't much I can do (as far as I know, at least).

**Comment by Loonygoose** [comment]
I've just switched to v2.2 and have transitioned all my subscriptions to use the youcast.cloudapp.net address. All but one throws an error 403. However, the error 403 does not occur when I use my internal Youcast server.

Not sure if you want me to post the username here for the youtube channel this fails on or I should PM it to you.
