### ISSUE TITLE
Support for individual video thumbnails

### ISSUE THREAD

**Issue by AsparagusEduardo** [i3arnon/YouCast#17]
I have noticed that some podcast feeds apply different thumbnails to each individual episode.
While not a necesary feature, it would be really useful to have the individual thumbnails of the videos in order to distinguish the videos from a glance.

**Comment by AsparagusEduardo** [comment]
Nevermind this issue, i didn't realized that the thumbnail was generated from the video itself ^^;

**Comment by i3arnon** [comment]
@AsparagusEduardo YouCast gets the thumbnail from YouTube. They automatically generate it from the video, but you can also replace it with something custom when you upload a video.
