### ISSUE TITLE
Error 403 

### ISSUE THREAD

**Issue by Loonygoose** [i3arnon/YouCast#19]
I've just switched to v2.2 and have transitioned all my subscriptions to use the youcast.cloudapp.net address. All but one throws an error 403. However, the error 403 does not occur when I use my internal Youcast server.

Not sure if you want me to post the username/xml file here for the youtube channel this fails on or I should PM it to you.

**Comment by i3arnon** [comment]
@Loonygoose here is fine, if you're still interested. But a PM is fine as well.
