### ISSUE TITLE
Failed Downloads

### ISSUE THREAD

**Issue by TiamatStudios** [i3arnon/YouCast#2]
I have noticed that any youtube videos that are blocked for various reasons such as potentially offensive just error out in the podcasts download. I use YouCast with MusicBee to manage my youtube podcasts. It always says failed and when I look up the video in question it gives me the confirm you wish to continue screen. I noticed it changes the youtube url to end with "&has_verified=1" without quotations. Only problem with just adding that I see is these videos always say sign in to unblock and adding &has_verified=1 to the end wont bypass it if you are not logged in. I am not sure there is an easy way around this issue that wouldn't involve adding login to youtube support. Anyway keep up the great work it is a highly useful program!

Update:
I did notice that going to www.TubeOffline.com and entering the video in question with &has_verified=1 at the end it can be downloaded from there without issues. Perhaps its possible to just add that to blocked videos or all videos to get rid of the errors?

**Comment by AndrejMartynov** [comment]
I had a similar problem that some videos required signing in or were not available in my country. I prefer to download such problem videos manually so I extended YouCast to read URLs from external file. YouCast creates an empty missing.<videoid> file when it fails to get a link, I download video manually, put it to a local web server and add URL to the missing.<videoid> file. YouCast reads the link form the file when my podcast application tries to download video next time.

Patch:
Index: YoutubeFeed.cs
===================================================================
--- YoutubeFeed.cs	(revision 33)
+++ YoutubeFeed.cs	(working copy)
@@ -134,19 +134,52 @@
 
         public void GetVideo(string videoId, string encoding)
         {
-            var resoultion = int.Parse(encoding.Remove(encoding.Length - 1).Substring(4));
-            var orderedVideos = DownloadUrlResolver.GetDownloadUrls(string.Format(VideoUrlFormat, videoId), false).
-                Where(_ => _.VideoType == VideoType.Mp4).
-                OrderByDescending(_ => _.Resolution).
-                ToList();
-            var video = orderedVideos.FirstOrDefault(_ => _.Resolution == resoultion) ?? orderedVideos.First();
-            if (video.RequiresDecryption)
-            {
-                DownloadUrlResolver.DecryptDownloadUrl(video);
-            }
-
-            WebOperationContext.Current.OutgoingResponse.StatusCode = HttpStatusCode.Redirect;
-            WebOperationContext.Current.OutgoingResponse.Headers["Location"] = video.DownloadUrl;
+            var resoultion = int.Parse(encoding.Remove(encoding.Length - 1).Substring(4));
+            var videoURL = "";
+            try
+            {
+                var orderedVideos = DownloadUrlResolver.GetDownloadUrls(string.Format(VideoUrlFormat, videoId), false).
+                    Where(_ => _.VideoType == VideoType.Mp4).
+                    OrderByDescending(_ => _.Resolution).
+                    ToList();
+                var video = orderedVideos.FirstOrDefault(_ => _.Resolution == resoultion) ?? orderedVideos.First();
+                if (video.RequiresDecryption)
+                {
+                    DownloadUrlResolver.DecryptDownloadUrl(video);
+                }
+                videoURL = video.DownloadUrl;
+            }
+            catch (YoutubeExtractor.YoutubeParseException)
+            {
+            }
+
+            var location = "";
+            var eraseFile = false;
+            var fileName = System.AppDomain.CurrentDomain.BaseDirectory + "missing." + videoId;
+            try 
+            {
+                location = Uri.EscapeUriString(System.IO.File.ReadAllText(fileName));
+            }
+            catch (System.IO.FileNotFoundException)
+            {
+            }
+            if (location == null || location.Length == 0)
+            {
+                location = videoURL;
+                eraseFile = true;
+            }
+            if (location == null || location.Length == 0)
+            {
+                System.IO.File.Create(fileName).Close();
+            }
+            else
+            {
+                if (eraseFile && System.IO.File.Exists(fileName))
+                    System.IO.File.Delete(fileName);
+            }
+            
+            WebOperationContext.Current.OutgoingResponse.StatusCode = HttpStatusCode.Redirect;
+            WebOperationContext.Current.OutgoingResponse.Headers["Location"] = location;
         }
 
         #endregion
