### ISSUE TITLE
The server encountered an error processing the request. See server logs for more details.

### ISSUE THREAD

**Issue by mikebarber1** [i3arnon/YouCast#20]
I get this error every once in a while when my podcast catcher application (Downcast) tries to download a new "episode" on some of my feeds.

How does one enable logging to see what is really going on and possibly troubleshoot?
I don't see any log files in the application directory and the config file doesn't have anything in it that screams turn me on for logging.

Thanks.

**Comment by i3arnon** [comment]
@mikebarber1 There's no way to turn logging on as I haven't written any logs. It's possible to add a logging framework and specific logs but I don't have any plans for doing that in the near future. The simplest way figure out what's going on inside is to debug the actual code.
Those failed episodes are usually the ones that require you to login with a YouTube account (e.g. explicit). If you have a feed that consistently fail you can create an issue and I'll try to look it over.
Sorry for not getting to your issue sooner.
