### ISSUE TITLE
Can somebody please help

### ISSUE THREAD

**Issue by billuk3** [i3arnon/YouCast#22]
I have had this software a while but still dont get the cloud service thing I want to run the rss feed from anywhere and alot of them for a project im trying to get running .
I have digital ocean server but I dont understand what im doing to get this to work.
Do i need a windows server and when the instructions say open port does that mean open a port on the firewall?
Thanks for any any help

**Comment by firain** [comment]
This is a windows application, so it would be better to use a windows environment to run it. But if you are running Linux on your digital ocean server, you can try to use wine to run it (never tried myself, not sure if it runs or not)
And yes, you need to open the port on the firewall to access it from outside of the local environment.

**Comment by i3arnon** [comment]
Hey @billuk3,
When I originally made YouCast it only worked locally, which meant that if you want to use it everywhere you need a Windows server (or PC) and make sure you can accept incoming connections to that server.
This requires knowing that server's public IP, opening the port YouCast uses in the firewall and for YouCast to always be running on that server.

Later I added the cloud option which means I host the YouCast server myself on Azure and so the YouCast app is only used to generate the url. You can also generate them yourself if you understand how.
The cloud option is much simpler. You don't need anything except an internet connection.

For example, here is the url for my personal channel: http://youcast.cloudapp.net/FeedService/GetUserFeed?userId=i3arnon&encoding=MP4_720p&maxLength=0&isPopular=False
You can easily see it's publicly hosted at youcast.cloudapp.net and the parameters are my channel name, the desired resolution and so forth.

I hope this makes everything clearer. I'm closing this issue but please tell me if you have any issues.
