### ISSUE TITLE
Error 403

### ISSUE THREAD

**Issue by richardwarriner** [i3arnon/YouCast#23]
I have been running this fine for months on a local windows machine but in the last 2 days all my feeds are showing 403 errors. The feed shows new videos as they are release but i can't view or download them without a 403 error.
Anything i can look at to resolve?

**Comment by i3arnon** [comment]
Hey @richardwarriner,
This should no longer be an issue with the current release (https://github.com/i3arnon/YouCast/releases/tag/2.3.0).
I'm closing this issue but please tell me if you have any issues.

**Comment by dawidcieszynski** [comment]
@i3arnon did you run this version youcast.cloudapp.net ?
I have error on few media from podcasts.

This do not work: http://youcast.cloudapp.net/FeedService/Audio.m4a?videoId=f-WKjGc05I0
But this works: http://youcast.cloudapp.net/FeedService/Audio.m4a?videoId=DxtfHOT_gw4
All from this: 
http://youcast.cloudapp.net/FeedService/GetPlaylistFeed?playlistId=PLNCZDi-RY4iFmUI6xpgypWxaWVfxL1sEZ&encoding=Audio&maxLength=0&isPopular=False

When I use YouCast.exe localy all works great.

**Comment by i3arnon** [comment]
@dawidcieszynski AFAIK not all videos that work locally will work with the cloud service as YouTube embeds an IP in the stream URL:
It sounds like that's the case with your playlist and I don't really know how to solve that.

<details>
<summary>Stream URL</summary>
https://r1---sn-jxnj5-cjoe.googlevideo.com/videoplayback?mt=1542626678&c=WEB&dur=1860.243&keepalive=yes&source=youtube&lmt=1541625165658184&ei=75_yW-uKOYft1gKn7ZTIBg&id=o-ABagLyZBl6KZS5Qe7VaENUGsdww_WQiypGo7E9PxNJWL&ms=au,rdu&gcr=ie&mv=u&mm=31,29&signature=391DE8E3FF28FAD358001911D29F3EBC01E97336.8AB1624BC287FF4C10E7A57F95009EC647D18CED&mn=sn-jxnj5-cjoe,sn-4g5ednll&sparams=clen,dur,ei,gcr,gir,id,ip,ipbits,itag,keepalive,lmt,mime,mm,mn,ms,mv,pl,requiressl,source,expire&key=yt6&<b>ip=191.239.209.91</b>&txp=5533432&gir=yes&fvip=2&itag=140&expire=1542648912&pl=20&ipbits=0&clen=30107131&requiressl=yes&mime=audio/mp4&ratebypass=yes
</details>

**Comment by dawidcieszynski** [comment]
@i3arnon ok, I understand, thanks.
The only solution will be to stream content through  your server, but it will quickly eat transfer.
Other thought I have is to spoof url somehow when getting stream url from youtube, something like: 
https://stackoverflow.com/a/3342660/840119
But I don't know if it will even work.

**Comment by gandadil** [comment]
Any news about this problem? I am receiving these errors more frequently now.
