### ISSUE TITLE
youcast died suddenly

### ISSUE THREAD

**Issue by mrt25** [i3arnon/YouCast#3]
Hello, 

hope this is still under development in some way as it's really a great utility - I've not been able to find any other way of downloading videos, which seems an intuitive thing you'd want to do for Youtube.

but - I was managing to download absolutely perfectly to beyondpod until about 6 weeks ago. despite the ip matching on my router+on YC settings+BP URLs, it seems something else changed elsewhere and since then none of my subscriptions respond to download requests. 

could upload a feed update log from beyondpod i guess - or is there something else i could try pls?

Tom

**Comment by i3arnon** [comment]
Hey @mrt25,
YouCast is indeed "alive" (even though I don't have much time to devote to it).
Does the issue still exists?
If so could you try browsing the url YouCast provides from both your PC and the device BeyondPod runs on and share the results?
(I'm assuming the device can't get to YouCast for some reason)

Thanks,
-Bar Arnon
