### ISSUE TITLE
Incorrect Content-Type header

### ISSUE THREAD

**Issue by qtlin** [i3arnon/YouCast#31]
Current value is `Content-Type: text/html; charset=UTF-8` which causes problems when opening links with browser. Based on other podcasts, for example ones from audioboom, the correct header must be `Content-Type: application/rss+xml; charset=utf-8`.

**Comment by qtlin** [comment]
Any chance this can be resolved? What part of application is responsible for supplying Content-Type header?

**Comment by i3arnon** [comment]
Please try this release and see if it helps: https://github.com/i3arnon/YouCast/releases/tag/2.17.0

**Comment by qtlin** [comment]
New Content-Type is present. I am surprised with the number changed lines this update required.
Unfortunately it did not solve my original problem - unable to share RSS link from one iPhone to another.
It appears that only Apple Podcasts links like https://podcasts.apple.com/us/podcast/the-john-batchelor-show/id589864479 are sent to Podcasts application while a real link to the same podcast https://audioboom.com/channels/4002274.rss is not sent to Podcasts and instead a dialogue asking to find an Apple Store application capable to parse RSS links is displayed and Apple Store application is opened. In earlier iOS versions Apple News is opened and unable to parse link error is shown.
