### ISSUE TITLE
v2.6 does not work for me as v2.1 drop in replacement.

### ISSUE THREAD

**Issue by qtlin** [i3arnon/YouCast#33]
I've been running v2.1 for several years with no issues besides #11. But v2.6 on the same Windows 7 system with same parameters results in "episode temporary unavailable" like message on an iPhone for every episode. Episodes list is updated correctly.
Testing podcast feed and episodes using wget didn't reveal anything abnormal.
Reverted back to v2.1 for now.

**Comment by KPMonkey** [comment]
Took a look at the code and YoutubeExplode needs updated. I was getting 404 for all videos, the latest release fixes this.

**Comment by qtlin** [comment]
v2.7 seems to work.
