### ISSUE TITLE
getting 404 errors on version 2.6

### ISSUE THREAD

**Issue by sch1308** [i3arnon/YouCast#36]
the youtube video list updates fine but no videos download. http://scottsplex.duckdns.org:22703/FeedService/GetUserFeed?userId=UCKoafhJ9dkAWaEvlXCiBBwA&encoding=MP4_720p&maxLength=0&isPopular=False is one example of my feeds. @i3arnon

**Comment by Loonygoose** [comment]
Getting the same issue for all my feeds as well. It happens in 2.5 too.

**Comment by sch1308** [comment]
@Loonygoose i still get the error on version 2.5

**Comment by Loonygoose** [comment]
After a few more days of using 2.5, I am actually getting two different types of errors - file not found and network connection lost errors. However, it doesn’t happen to all my downloads like in 2.6, only some of them.
I’m testing to see if it is actually affected by the difference in location (and therefore IP address) as to when the feed is refreshed and download url generated vs when you actually do the download. 

It’s weird, as some of the ones I have failing now are part downloaded. I also don’t know what to make of the network connection lost errors as I don’t seem to be getting network errors for anything else.

**Comment by sch1308** [comment]
![Screenshot_20190925-203157_Podcast Addict](https://user-images.githubusercontent.com/7896067/65649278-e1bf1280-dfd3-11e9-9bff-463ff558313a.jpg)

**Comment by gandadil** [comment]
I have the same problem. All my downloads are 404 since install 2.6.

**Comment by i3arnon** [comment]
Are you using the "cloud service" or your local machine?

**Comment by prenfic** [comment]
> Are you using the "cloud service" or your local machine?

same issue, merely working with the local network, but frozen with the cloud (youcast.cloudapp.net). Gentleman, is your cloud currently not working anymore???

**Comment by i3arnon** [comment]
@prenfic It's indeed not working. Sorry.
https://github.com/i3arnon/YouCast/issues/41

**Comment by gandadil** [comment]
I think the problem is not the cloud service but the version of YouCast. If you run version 2.6 on your cloud, so it's not working because 2.6 is not working local too. I reverted to previous version 2 months ago.

**Comment by oolyum** [comment]
Getting the 404 issue with a few different versions running on local.  For giggles, I tried Podsync as well, and the same issue is happening with that service.  YouTube possibly messing things up again?

**Comment by jparkerweb** [comment]
@oolyum I had the same thing happening with both v2.7.0 of YouCast and Podsync web service.  Checkout my comment on what I think is a related recent issue here:
https://github.com/i3arnon/YouCast/issues/43#issuecomment-572701381

I am able to download all files without issue now for the past 24 hours.

**Comment by gandadil** [comment]
I still have the same problem (404 errors) with 2.8.0 version. My workaround was back to version 2.5 but this is not working anymore.
