### ISSUE TITLE
some videos can't be downloaded by youcast but youtube-dl has no problems.

### ISSUE THREAD

**Issue by qtlin** [i3arnon/YouCast#42]
```
wget -S 'http://my-youcast-pc:22703/FeedService/Video.mp4?videoId=xxxxxxxxx&encoding=MP4_360'
HTTP request sent, awaiting response... 
  HTTP/1.1 400 Bad Request
  Content-Length: 1647
  Content-Type: text/html
  Server: Microsoft-HTTPAPI/2.0
  Date: Mon, 30 Dec 2019 04:32:26 GMT
2019-12-29 23:32:26 ERROR 400: Bad Request.
```
There are no logs or reasons for a "Bad Request". How to debug the error? Sometimes youtube makes video available for youcast later, sometimes it is permanently not available.
Youtube-dl is always able to download the same video.
```
$ youtube-dl -f 18 xxxxxxxxx
[youtube] xxxxxxxxx: Downloading webpage
[youtube] xxxxxxxxx: Downloading video info webpage
[download] Destination: video_name-xxxxxxxxx.mp4
[download] 100% of 11.33MiB in 00:00
$
```

**Comment by sch1308** [comment]
I still get a 404 error on version 2.7 running locally, I was able to download two videos then the third one gave the 404 error.

**Comment by qtlin** [comment]
This is on v2.7 running locally. Just tried to open a random video, `JqEKjuol_T0` and got the same error 400.
At the same time, another random video, `ssUPdJsTv0A` opens with no problems:
```$ wget -S 'http://youcast-pc.ybk.name:22703/FeedService/Video.mp4?videoId=ssUPdJsTv0A&encoding=MP4_320'
--2019-12-31 20:08:40--  http://my-youcast-pc:22703/FeedService/Video.mp4?videoId=ssUPdJsTv0A&encoding=MP4_320
HTTP request sent, awaiting response... 
  HTTP/1.1 302 Found
  Content-Length: 0
  Location: https://r2---sn-gjo-cvne.googlevideo.com/videoplayback?.......
  Server: Microsoft-HTTPAPI/2.0
  Date: Wed, 01 Jan 2020 01:08:41 GMT
```

**Comment by justin-parker** [comment]
having the same issue.
for a youtube channel I have setup:
* not working: `VybBNsJQFPg`
* working: `ibrQBQOzWfs`

Please help!

**Comment by jparkerweb** [comment]
@qtlin @sch1308 checkout my comment on a related issue here:
https://github.com/i3arnon/YouCast/issues/43#issuecomment-572701381
See if that works for you?

**Comment by qtlin** [comment]
@jparkerweb I verified that `JqEKjuol_T0` opens with v2.7.1

**Comment by jparkerweb** [comment]
PR created:
https://github.com/i3arnon/YouCast/pull/44

**Comment by jparkerweb** [comment]
@qtlin can we close this issue now?

**Comment by qtlin** [comment]
v2.8 is good now.
