### ISSUE TITLE
Random(?) videos not downloading

### ISSUE THREAD

**Issue by EricJCross** [i3arnon/YouCast#43]
I am also experiencing what seems to be random videos which fail to download.

Without logs I am having trouble seeing what the errors are.  
But I have some information and examples for you.

I am seeing this issue in YouCast 2.2 - 2.7.  On feeds that have previously worked.  I am using iTunes to watch videos.  Although I can replicate the errors using a web browers pointing to the url, pointing to my local YouCast which I have running on 192.168.86.33.

YouTube videos:  https://www.youtube.com/channel/UC8fg8L4X7qpQdHJgxpM4qxw/videos
A working video from the channel above through YouCast:
http://192.168.86.33:22703/FeedService/Video.mp4?videoId=tOVOwOoUdxg&encoding=MP4_720
A non-working video from the channel above through YouCast:
http://192.168.86.33:22703/FeedService/Video.mp4?videoId=MXhviKutyRY&encoding=MP4_720

From a browser, if I use the working and non-working links above - 
working - the link is redirected to the YouTube video as:  https://r6---sn-5uaezn6r.googlevideo.com/videoplayback?expire=1578002309&ei=JRMOXuXpHIyPzLUPiLGLoA4&ip=47.4.194.96&id=o-ALtqOLbESLGIoz75cbZUDWxzI8Q0pDSFcCIuvFUmM_ls&itag=22&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-5uaezn6r%2Csn-p5qs7ner&ms=au%2Conr&mv=m&mvi=5&pl=20&initcwndbps=2116250&mime=video%2Fmp4&ratebypass=yes&dur=225.814&lmt=1574722275592927&mt=1577980618&fvip=6&fexp=23842630%2C23860862&c=WEB&txp=2316222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cratebypass%2Cdur%2Clmt&sig=ALgxI2wwRQIhAJHTfGOHrIClL1UDTcdu_XHX-cFTvf6h16tFNCqJbgmeAiBcixfsQHkMwsYkRQdbcirQssUkv4V_hJwBBnbOzI0xqQ%3D%3D&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRAIgHYVqWhJAKvBZDiUo3s1kS10iZgVjNh3RH6k_N4e4kw0CIDVwTDM1vxG9QRXkja7haE4cTNigBqhVwJeSaoE7Dt0z

non-working: 
I do not get the redirected link and only see the following output.
This 192.168.86.33 page can’t be foundNo webpage was found for the web address: http://192.168.86.33:22703/FeedService/Video.mp4?videoId=MXhviKutyRY&encoding=MP4_720

As I cannot see the logs any further, I cannot see if there are problems in generating the links properly, or if YouTube is blocking the content somehow, or something else.

**Comment by justin-parker** [comment]
having the same issue as of late.
please help!

**Comment by jparkerweb** [comment]
So I downloaded the solution and found that the YoutubeExplode library had an update available.  I updated and rebuilt the app and all downloads seem to be working fine for me now with my custom build.  @EricJCross give it a shot and let me know if that fixes it for you please.  If so I can create a PR for @i3arnon to just update the library.  

Find my fork/built binaries here:
https://github.com/jparkerweb/YouCast/releases/tag/2.7.1

**Comment by EricJCross** [comment]
Really good catch @jparkerweb !   I was just testing against Podsync and noticed it was failing against the same videos on the same feeds.  So it had to be something on youtube.  And I was going through the code on each but wasn't seeing anything yet.  Didn't think to compare the libraries.  

I downloaded your version, and, so far, everything which was failing on my end is now successfully downloading.  I believe you've fixed the issue.  Please create the PR for @i3arnon .  Well done.
Thanks bud.

**Comment by jparkerweb** [comment]
PR created:
https://github.com/i3arnon/YouCast/pull/44

**Comment by gandadil** [comment]
@jparkerweb your version is working!!!! Thanks a lot.

**Comment by jparkerweb** [comment]
@gandadil, @i3arnon merged my PR and released a new version today (https://github.com/i3arnon/YouCast/releases/tag/2.8.0) with the fix :)

I think this issue should probably be closed.
