### ISSUE TITLE
GetUserFeed request stopped working

### ISSUE THREAD

**Issue by qtlin** [i3arnon/YouCast#45]
Running latest, v2.8
Several days ago accessing URL FeedService/GetUserFeed?userId=.... stopped working, returns an HTTP error 400 with message:

`The server encountered an error processing the request. See server logs for more details.`

At the same time URL FeedService/Video.mp4?videoId=... etc. works fine.

Is it only for me or another YouTube change? There is new YoutubeExplode release and the change seems channel list related, although seems minor.

**Comment by i3arnon** [comment]
YouTube revoked the application key.
I generated a new one and released a new version:
https://github.com/i3arnon/YouCast/releases/tag/2.9.0

See if this works for you and let me know otherwise.

**Comment by oolyum** [comment]
This seems to working.  Thanks.

**Comment by i3arnon** [comment]
@oolyum thank you.

**Comment by mrDLSable** [comment]
I'm running 2.9 and it worked yesterday, but it's once again giving the request error. The video page still works but the feeds not @i3arnon

**Comment by i3arnon** [comment]
@mrDLSable The quota for the new API key (10K requests per day) is being reached daily.
Since I assume this isn't from "real" usage I regenerated the key (without pushing it to GitHub this time :)):
https://github.com/i3arnon/YouCast/releases/tag/2.10.0

The quota will be reset tomorrow. If it will max out again I'll maybe try adding some caching, but it's just a band-aid.

**Comment by mrDLSable** [comment]
@i3arnon Is it possible to get the app to load the API key from the config file? That way people with the know how could use their own key.

**Comment by qtlin** [comment]
@i3arnon I was about to ask the same question but @mrDLSable was minutes ahead of me.
Please allow user optionally loading their own key and add instructions getting one from Google. Thank you.

**Comment by jparkerweb** [comment]
for now I was able to generate my own youtube data api key and build from source with my own key.  seems to work great.....

example of my api key management screen in google:
![image](https://user-images.githubusercontent.com/3073864/75178106-49e16400-56ec-11ea-91ce-52242959973a.png)

**Comment by i3arnon** [comment]
@mrDLSable Sure: https://github.com/i3arnon/YouCast/issues/46

**Comment by qtlin** [comment]
@jparkerweb thanks for the suggestion to create a key and rebuild from source. It does indeed work but user needs to enable `YouTube Data API v3`. It took me some time to realize it but it all works now.

**Comment by superfutzi** [comment]
For a noob like me, how can I set it up in the program code. I got an APi but I don`t know how the create an exe.

**Comment by maxol18** [comment]
Hi,

On my side is version v2.10 not working.

Is it working on your side ?

**Comment by mrDLSable** [comment]
I have done some playing around with my own API key and have found out that for me a normal refresh with Podcast Addict generates over 4k requests. Do keep in mind that I have about 100 youtube channels in my podcast library and about 40 new videos to download.

**Comment by maxol18** [comment]
> For a noob like me, how can I set it up in the program code. I got an APi but I don`t know how the create an exe.

Hi,

I dont also know how to compile in .exe

**Comment by mrDLSable** [comment]
@maxol18 @superfutzi I have written the code needed for the user to input their API key in the program, and once @i3arnon has some time to look at it, I presume the functionality will be added. It should be done in a couple of days I hope.

**Comment by i3arnon** [comment]
#47 is now merged and [a new release is published](https://github.com/i3arnon/YouCast/releases/tag/2.11.0),
Thank you @mrDLSable and sorry for the wait.. I was in Iceland.

**Comment by qtlin** [comment]
@i3arnon the same exact problem resurfaced again, youcast apparently requires latest YoutubeExplode update to function correctly. However YoutubeExplode 5.x is not a direct replacement for 4.x. Please take a look when you have a chance.

**Comment by i3arnon** [comment]
@qtlin I incorporated YoutubeExplode's latest version and [published a new release](https://github.com/i3arnon/YouCast/releases/tag/2.12.0)
Hope this helps..

**Comment by mrDLSable** [comment]
I'm still getting the error 400 with some channels...

**Comment by i3arnon** [comment]
@mrDLSable Give me some examples and I'll try to debug..

**Comment by mrDLSable** [comment]
vsauce works (channelID: vsauce)
half as interesting doesn't work (channelID: UCuCkxoKLYO_EQ2GeFtbM_bw)

**Comment by mrDLSable** [comment]
A couple more that don't work:
UCVQCQJyZQcIioTDQ4SACvZQ
UC0e3QhIYukixgh5VVpKHH9Q
UCrv269YwJzuZL3dH5PCgxUw
UC6SNxiLzSlh8e0yjndE9o_A
UCaPRCWnFAzeI3_tr--Qw5qg
UCzV9N7eGedBchEQjQhPapyQ

**Comment by i3arnon** [comment]
@mrDLSable There was an issue with channel ids (as opposed to usernames). The updated release should work

**Comment by mrDLSable** [comment]
2.13 or still 2.12?

**Comment by i3arnon** [comment]
@mrDLSable still 2.12 :)

**Comment by mrDLSable** [comment]
Works for me now :) Thanks for the quick fix

**Comment by mrDLSable** [comment]
actually now channels with a name don't work

**Comment by mrDLSable** [comment]
example: crashcourse

**Comment by i3arnon** [comment]
@mrDLSable fixed and updated.

**Comment by mrDLSable** [comment]
Testing it now. Looks like it's working. Thanks again for the quick update. Love the app.

**Comment by qtlin** [comment]
@i3arnon Thank you! 2.12 so far works for me.
Question: should anyone worry about new commits [one](https://github.com/i3arnon/YouCast/commit/334189d639e48ac91729727a34d9059d24c5c588) [two](https://github.com/i3arnon/YouCast/commit/565822646061ce19a27f3e8400e9b695690e2a74) since release 2.12 and build own from master or 2.12 is good as is?

**Comment by mrDLSable** [comment]
@qtlin v2.12 includes those two commits. I don't know how it works but I think @i3arnon can upload a new version of the files to an existing release

**Comment by maxol18** [comment]
Hi,

Is the last version 2.12 working on you side ?

**Comment by qtlin** [comment]
> Is the last version 2.12 working on you side ?
Even 2.18 works fine for me
