### ISSUE TITLE
Install for version 2.11

### ISSUE THREAD

**Issue by rprevans** [i3arnon/YouCast#48]
I can see version 2.11 has been recently posted here.  I can only see the source code as available for download, I can't see the installer?

**Comment by i3arnon** [comment]
Of course you can't.. because I haven't uploaded it.
It's there now.. thanks.

**Comment by rprevans** [comment]
> Of course you can't.. because I haven't uploaded it.
> It's there now.. thanks for letting me know.

Thanks!
Ray
