### ISSUE TITLE
App closes when minimizing the window

### ISSUE THREAD

**Issue by jamesqo** [i3arnon/YouCast#5]
Hey, just tested out your app and it's really great! For some reason though, it closes whenever I try minimizing the window; I can see it's still alive in Task Manager but its icon disappears from the taskbar. Could you look into it?

-James

**Comment by i3arnon** [comment]
Hi,
Thanks for taking a look.
YouCast minimizes itself to the system tray when minimized.
It feels more natural since it's always alive in the background.
I assume that's why you're seeing it in the Task Manager.
