### ISSUE TITLE
"unable to open its ChannelListener

### ISSUE THREAD

**Issue by sch1308** [i3arnon/YouCast#51]
Im getting the following error when changing the api key to my own. 
![image](https://user-images.githubusercontent.com/7896067/77236122-f7338480-6b91-11ea-9d1c-84dfcd48e0ad.png)

it seems like its communicating because im getting counts on the api key. 
![image](https://user-images.githubusercontent.com/7896067/77236159-45488800-6b92-11ea-8cdb-d31f2224c051.png)

**Comment by i3arnon** [comment]
Did you update both the Application Name and the API Key?
Have you configured the API key with these options?
![image](https://user-images.githubusercontent.com/6595156/77245859-b0459d80-6c2a-11ea-834e-dca43ad9d620.png)

**Comment by sch1308** [comment]
followed the questionnaire and I had the right API selected. 
![image](https://user-images.githubusercontent.com/7896067/77253634-d6bb0700-6c31-11ea-8045-42b574575f10.png) It seems like the normal youtube channels download fine but not the music channels? 
![image](https://user-images.githubusercontent.com/7896067/77253774-f9015480-6c32-11ea-97a8-f9431045c437.png)
