### ISSUE TITLE
Getting error 400 on certain YouTube channels. 

### ISSUE THREAD

**Issue by sch1308** [i3arnon/YouCast#56]
I'm getting the "bad syntax error" on some of my podcast links. My YouTube api quota is only about 2,000 requests per day, well below the 10,000 allowed. I have tried deleting and readding the feed to my podcast app as well. Any other suggestions? 
![Screenshot_20200514-103203_Podcast Addict](https://user-images.githubusercontent.com/7896067/81947140-35678600-95ce-11ea-9a58-5eb913973823.jpg)

**Comment by maxol18** [comment]
Hi,
I also have no updates on the podcasts.

Best Regards.

**Comment by ykne** [comment]
Same here. Starting from May 12th evening some of my feeds return:
```
  <body>
    <div id="content">
      <p class="heading1">Request Error</p>
      <p>The server encountered an error processing the request. See server logs for more details.</p>
    </div>
  </body>
```
Would be nice to be able to return actual youtube error instead of generic one.

**Comment by KPMonkey** [comment]
Service.YoutubeFeed Object reference not set to an instance of an object.System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)

**Comment by ykne** [comment]
Existing links `GET /FeedService/Video.mp4?videoId=....` to previously fetched feed items still work.
I believe similar happened once before and required youtube component update.

**Comment by i3arnon** [comment]
I incorporated YoutubeExplode's latest version and [published a new release](https://github.com/i3arnon/YouCast/releases/tag/2.12.0)
Hope this helps..

**Comment by maxol18** [comment]
Hi,

I tried the version 2.12 and have no update in my podcasts.

Best Regards

**Comment by maxol18** [comment]
Hi,

I Tried the last version 2.12 ans it is not working.

Is it working by someone ?

Best Regards

**Comment by mrDLSable** [comment]
Could you please tell us exactly which parts aren't working? Is it with a channel or a playlist? And what is the channel or playlist ID?
________________________________

**Comment by maxol18** [comment]
Hi,

No podcast is updating it was working last time on friday.

For example channel id UC48MclMZIY_EaOQwatzCpvw

Best Regards

**Comment by mrDLSable** [comment]
Did you remember to input your own API key after you updated? The app doesn't store settings between updates.

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by maxol18** [comment]
Hi,

Indeed i forgot.

I want to thank you. It works now

Best regards

**Comment by mrDLSable** [comment]
You're welcome.

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________
