### ISSUE TITLE
Unwanted Caching in Application?

### ISSUE THREAD

**Issue by qtlin** [i3arnon/YouCast#61]
The initial FeedService/Video.mp4 on a just finished live transaction almost always fails because it takes some time for YouTube to provide acceptable encodings. However even after all necessary encodings are available the FeedService/Video.mp4 request still fails unless YouCast.exe is restarted.

Could YouCast reset YouTube connection or do anything else necessary to avoid this problem? Stream details are in #60

**Comment by i3arnon** [comment]
The caching made sense for the cloud.
It's not really necessary anymore so I removed it:
https://github.com/i3arnon/YouCast/releases/tag/2.15.0

**Comment by qtlin** [comment]
2.15.0 was working yesterday but does not return GetUserFeed today. Reverted back to previous. No error log makes any kind of diagnostic impossible.

**Comment by i3arnon** [comment]
Works for me. Do you want to give me the username to check?
Could it be that your client requests too often and your IP got blocked? That's why I added the cache originally.
Would you try resetting the router to get a new IP and try again?

**Comment by qtlin** [comment]
Previous works in the same IP. No feed is returned by 2.15.0 today. Stop 2.15.0, start previous on the same system and all feeds are returned. I picked up a random YouTube user for testing: gordonramsay
