### ISSUE TITLE
Unable to subscribe to newer channels - new youtube format?

### ISSUE THREAD

**Issue by qtlin** [i3arnon/YouCast#64]
Many new youtube channels now show up as /c/username, previous format was /user/username. Does youcast need an update? Only /user/username format feeds can be subscribed to via GetUserFeed?userId= URL.
UPD: for /c/username channels enter username in youtube search and the same channel may come up with /channel/longusername url and then longusername is accepted by youcast.

**Comment by qtlin** [comment]
I don't see this possibly fixed anytime soon. Since workaround exists, I am closing this issue.

**Comment by i3arnon** [comment]
The YouTube API doesn't offer a way to go from a channel's custom url to the channel itself (e.g. channel ID), so the workaround is currently the best option.

**Comment by qtlin** [comment]
Unfortunately workaround does not seem to work anymore.
