### ISSUE TITLE
playlistId and YouTubeEncoding not saving to config

### ISSUE THREAD

**Issue by semihselcuk** [i3arnon/YouCast#66]
I believe these two values are not saved to "user.config". This is the reason every time I restart the app sections are empty. 

Would it be possible to save them to config so we do not need to fill our selection again and again?

ApiKey, ApplicationName and StartupWindowState are being saved to config and app can retrieve after startup.

**Comment by i3arnon** [comment]
Those are "saved" in the url YouCast generates. After you got the url you don't have to choose those values ever again.
How do you use YouCast? Where do you copy that url over to?

**Comment by semihselcuk** [comment]
Hey @i3arnon  thanks for your answer. 
Yes, you are right I don't have to enter the values again. Once is enough.
I run YouCast on my local PC and use the url over Podcast Addict. 
It works like a charm!
