### ISSUE TITLE
Update of episodes ok but no download of episodes

### ISSUE THREAD

**Issue by maxol18** [i3arnon/YouCast#67]
Hi,

Since yesterday Update of episodes ok but no download of episodes

V2.18

Is it a general issue ?

best regards

**Comment by danoscolaterais** [comment]
> Hi,
> 
> Since yesterday Update of episodes ok but no download of episodes
> 
> V2.18
> 
> Is it a general issue ?
> 
> best regards

Yes, same here.

**Comment by qtlin** [comment]
Check if your IP is blacklisted for YouTube. Test it by changing location or use cellular data. ip4.me is your friend here.

**Comment by kane2742** [comment]
I've had a similar issue before, and it does seem to be specific to a particular IP address, like qtlin suggested. My issue went away if I used a VPN or had YouCast run on a different PC (and generated the feed URLs from there). 

The last time I had this issue, it was right after I added multiple subscriptions in one day. My best guess is that the large number of requests (all those back episodes) in a short amount of time was more than some allowed limit per hour, day, etc., so YouTube blocked that IP address from getting any more videos.

I just downloaded a video to test that it's currently working for me. It is, so it's not an issue for all YouCast users.

**Comment by danoscolaterais** [comment]
> I've had a similar issue before, and it does seem to be specific to a particular IP address, like qtlin suggested. My issue went away if I used a VPN or had YouCast run on a different PC (and generated the feed URLs from there).
> 
> The last time I had this issue, it was right after I added multiple subscriptions in one day. My best guess is that the large number of requests (all those back episodes) in a short amount of time was more than some allowed limit per hour, day, etc., so YouTube blocked that IP address from getting any more videos.
> 
> I just downloaded a video to test that it's currently working for me. It is, so it's not an issue for all YouCast users.

So, i've changed the external IP address by rebooting the router and it didn't work, also created a new API from other google account and still not working. I've noticed that there's a new cookie consent window a couple days ago, could that be the reason?

**Comment by maxol18** [comment]
Hi,

I have changed the API Key and tried with an other computer.

Still no download.

**Comment by maxol18** [comment]
Hi,

I just retried and it is nowworking.

Very strange
