### ISSUE TITLE
Error 404 on all Videos

### ISSUE THREAD

**Issue by superfutzi** [i3arnon/YouCast#68]
Hi all,

since yesterday I get an 404 on every video I tried to download (about 10). I changed my API but still 404.

**Comment by semihselcuk** [comment]
Have the same issue. Looks like endpoint is not found.

e.g
http://192.168.1.7:22703/FeedService/Audio.m4a?videoId=TQl4gF0F-nA

![image](https://user-images.githubusercontent.com/997614/115114269-4e1eaf80-9f86-11eb-85b9-e3d826f95095.png)

**Comment by maxol18** [comment]
Hi,

Same issue here.

Epidodes are updating but no download

**Comment by maxol18** [comment]
Hi,

Is it working by someone ?

**Comment by qtlin** [comment]
Have you tried moving the system where youcast is installed to another IP address? For example, try any free VPN service providers. To debug you may run YoutubeExplode client directly, either UI or command line and see if any errors. Command line client will show exact youtube error(s) if any. UI will just error out. BTDT.
https://github.com/Tyrrrz/YoutubeExplode/issues/483#issuecomment-739481527

**Comment by maxol18** [comment]
Hi,

Sorry how can we run YoutubeExplode ?

**Comment by qtlin** [comment]
@maxol18 please follow the link to a comment in issue 483 above. It has instructions.

**Comment by maxol18** [comment]
Hi,

I receive error 404 on all video trying to download.

**Comment by maxol18** [comment]
Hi,

Is youcast still working for someone ?

**Comment by i3arnon** [comment]
I've released a version with the latest YoutubeExplode update: https://github.com/i3arnon/YouCast/releases/tag/2.19.0
Please try it out

**Comment by semihselcuk** [comment]
Just tried. Same error.

**Comment by sean89503** [comment]
@semihselcuk @maxol18  what app are you using to play your podcast?

**Comment by semihselcuk** [comment]
@sean89503 [Podcast Addict](https://play.google.com/store/apps/details?id=com.bambuna.podcastaddict)

**Comment by sean89503** [comment]
> @sean89503 [Podcast Addict](https://play.google.com/store/apps/details?id=com.bambuna.podcastaddict)

I was thinking maybe it was a server side app but that's not the case

**Comment by semihselcuk** [comment]
@sean89503 app was working perfectly. Then started giving me 404 errors but still keeps the podcasts updated.

**Comment by maxol18** [comment]
> @semihselcuk @maxol18 what app are you using to play your podcast?

Hi

I'am using apple podcast

**Comment by maxol18** [comment]
> I've released a version with the latest YoutubeExplode update: https://github.com/i3arnon/YouCast/releases/tag/2.19.0
> Please try it out

Hi,

I just tried. The podcast are updating but no dowload.

**Comment by qtlin** [comment]
Has anyone with error 404 tried running YoutubeExplode demo directly?
https://github.com/i3arnon/YouCast/issues/68#issuecomment-826367630

**Comment by kane2742** [comment]
For me, version 2.18 is working, but 2.19 isn't. I went back to 2.18, and I'm not having any issues with it.

Has everyone who's having issues tried qtlin's suggestion of using a VPN to see if it's an IP address issue? I don't remember the details, but I think YouTube will (temporarily?) block your IP address if you exceed a certain number of requests in a certain amount of time. Using a VPN can get around that. The free version of [ProtonVPN ](https://protonvpn.com/download) worked for me when I had a similar issue in the past. It's generally slower than without the VPN, though, so I only use it as needed.

**Comment by sean89503** [comment]
> > @semihselcuk @maxol18 what app are you using to play your podcast?
> 
> Hi
> 
> I'am using apple podcast

Im tring to think outside of the box so sorry if i have all these questions, but do you use unlimited quality ?
Google API only has limit  around 10,000 so if its checking all the history every time by time it gets to download you already exceed the api limit, you can see at https://console.cloud.google.com/apis/api/youtube.googleapis.com/quotas? if  your hitting it.

**Comment by semihselcuk** [comment]
I am actually using for Audio only. And so far I had 40 videos on my playlist. 
Of course not sure how many request happen at the background.

**Comment by mrDLSable** [comment]
I'm also getting 404s on all video downloads since today... until yesterday it worked fine... very strange...

**Comment by maxol18** [comment]
Hi,

Is there an updated working version ?

Thank you.

**Comment by qtlin** [comment]
@maxol18 Have you performed your IP address test by running YoutubeExplode directly?
https://github.com/i3arnon/YouCast/issues/68#issuecomment-831232302
Also please be advised that completed live stream videos take about an hour or more to be processed by YouTube to be available for YouCast download.

**Comment by mrDLSable** [comment]
I think that updating youtube explode to 6.0.1 now that it is out would fix this issue @i3arnon

**Comment by i3arnon** [comment]
> I think that updating youtube explode to 6.0.1 now that it is out would fix this issue @i3arnon

There you go: https://github.com/i3arnon/YouCast/releases/tag/2.20.0
Thank you for the heads-up

**Comment by semihselcuk** [comment]
@i3arnon Just tried and it works! Thanks everyone.

**Comment by qtlin** [comment]
@superfutzi or @i3arnon please close this, too many issues stay open needlessly.
