### ISSUE TITLE
Error 400

### ISSUE THREAD

**Issue by superfutzi** [i3arnon/YouCast#69]
Since a day or so, I can't keep my feeds up to date. When synchronizing I get: "Error 400: The request cannot be fulfilled due to bad syntax..." I tried both with Podcast Addict on my phone as well with the browser on my PC.

**Comment by danoscolaterais** [comment]
> Since a day or so, I can't keep my feeds up to date. When synchronizing I get: "Error 400: The request cannot be fulfilled due to bad syntax..." I tried both with Podcast Addict on my phone as well with the browser on my PC.

Same happened to me.

**Comment by danoscolaterais** [comment]
> Verify your YouTube API key?

That's it, i forgot to change it when i moved to other PC a few days ago. Thank you.

**Comment by qtlin** [comment]
@superfutzi  Please close this issue.
