### ISSUE TITLE
Does not work with Pocketcasts

### ISSUE THREAD

**Issue by MinorSingingAirhead** [i3arnon/YouCast#75]
Every URL I generate results in "Unable to find a podcast at this URL"
Help, please?

**Comment by qtlin** [comment]
does it work with AntennaPod or other readers?

**Comment by MinorSingingAirhead** [comment]
No. I tried AntennaPod and Google Podcasts.

Am Mo., 14. März 2022 um 04:13 Uhr schrieb qtlin ***@***.***>:

**Comment by MinorSingingAirhead** [comment]
I used it with the API that was already entered 😅
I suppose I need to get a different API somehow...

qtlin ***@***.***> schrieb am Di., 15. März 2022, 20:08:

**Comment by qtlin** [comment]
you must create and use your own API keys.
