### ISSUE TITLE
Youcast dont download since 2 days

### ISSUE THREAD

**Issue by maxol18** [i3arnon/YouCast#77]
Hi,

I have version 2.21 and since 2 days no update or download of youcast.

i tried to updated the api key but it dont help.

Is it working for others ?

**Comment by qtlin** [comment]
yes, as usual. please try running YoutubeExplode cli demo, may be youtube errors are shown.
YouCast does not deliver any errors that may be reported from YoutubeExplode backend.
once I had my IP rejected for a while for some reason and only YoutubeExplode cli demo showed the error.

**Comment by maxol18** [comment]
Strange no error in the iphone app podcast no update of podcast.

In itunes in the computer podcast are updated.

**Comment by maxol18** [comment]
Hi,

Issue is solved.

the windows firewall was blocking the requests
