### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by orschiro** [i3arnon/YouCast#8]
Dear @i3arnon,

Thank you for this promising tool!

Do you have any plans of supporting Linux?

Thankfully,

~Robert

**Comment by i3arnon** [comment]
Hey @orschiro,
This is very unlikely as YouCast is written in .Net which doesn't run on Linux.
There used to be RSSHandler written in Java but I don't think anyone is behind it anymore.
I did however manage to make a YouCast cloud service on Azure but I haven't had the chance to build a UI for it yet.

**Comment by orschiro** [comment]
Dear @i3arnon,

Thanks for your reply!

I have found an alternative for Linux users in the meanwhile: http://podsync.net/

Maybe it's also interesting to you.

Warmly,

~Robert
