### ISSUE TITLE
Youtube Explode outdated causes problem

### ISSUE THREAD

**Issue by mrDLSable** [i3arnon/YouCast#80]
YouTube Explode is currently outdated, which causes some videos to give the error "The following content is not available on this app." Updating YouTube Explode will hopefully fix this issue.

Relevant YoutubeExplode issue: https://github.com/Tyrrrz/YoutubeExplode/issues/647

![Screenshot_20221020-130736_Podcast Addict.jpg](https://user-images.githubusercontent.com/1783781/196932908-0e5da719-afa1-4d35-a777-37c1c7173e3d.jpg)

**Comment by i3arnon** [comment]
Updated all dependencies: https://github.com/i3arnon/YouCast/releases/tag/2.22.0

My test videos also worked with the older version, so I hope this helps, but can't make sure.

**Comment by mrDLSable** [comment]
Haven't had an issue yet today while watching a couple dozen video's. So maybe it needed a while to solve? Very strange
