### ISSUE TITLE
Weird download issues

### ISSUE THREAD

**Issue by mrDLSable** [i3arnon/YouCast#85]
The past couple of days I've been having some weird issues downloading videos. Sometimes, YouCast will refuse to download a specific video giving it a 404 error from my podcatcher, but then a couple of hours later it is magically fixed. I have restarted the server, which did not fix it. Downloading the video in the browser has firefox showing me an error saying "No video with supported format and MIME type found." The network analyzer in the debug tools in firefox says the status is 404.

The current video that is giving me this issue is ```cPj8baxGbIk```, but I presume that by the time you will read this in a couple of hours, it will have started working again and tomorrow another video will start acting up...

I hate bugs that aren't always present...

Edit:
The previous video that also gave me this issue but has since started working again is ```tng7PsWxEbE```

Edit2:
Now all downloads 404...

**Comment by oddtoddy** [comment]
Noticed this as well yesterday. Thought it was my quota but apparently not.

**Comment by mrDLSable** [comment]
> Noticed this as well yesterday. Thought it was my quota but apparently not.

Nope, I'm still way below my quota as well. 

I actually just noticed the video that I thought had fixed itself, has now unfixed itself and is giving me 404 again...

**Comment by oddtoddy** [comment]
Thinking it's probably just some Youtube server issues maybe?

**Comment by mrDLSable** [comment]
It could be that youtube has updated their api in some way. I just checked and Youtube Explode https://github.com/Tyrrrz/YoutubeExplode has had quite a few updates in the past 6 months since hte last YouCast update. This is the abstraction layer of the youtube API, so it could be that an update of Explode will be the simple magical fix

**Comment by mrDLSable** [comment]
I don't currently have .NET installed or a fork of YouCast downloaded so I haven't been able to test this for myself.

@sean89503 I know that you are running a newer Explode version on your fork. Are you having this issue as well?

**Comment by mrDLSable** [comment]
Now all downloads 404

**Comment by IWScout** [comment]
I had the occasional download work, otherwise all failing for me as well.

**Comment by oddtoddy** [comment]
Seems like 2 of 10 work for me at the moment. Will probably need to use NewPipe in the meantime or something.

**Comment by mrDLSable** [comment]
Temporary fix available in Pull Request #86 .

**Comment by i3arnon** [comment]
Hey all,
I've updated the dependencies and released a new version: https://github.com/i3arnon/YouCast/releases/tag/2.23.0
Thank you for keeping this (and me) updated..

**Comment by mrDLSable** [comment]
Thanks for the update. I'll close this issue and remove the temp file now.

**Comment by oddtoddy** [comment]
> Hey all, I've updated the dependencies and released a new version: https://github.com/i3arnon/YouCast/releases/tag/2.23.0 Thank you for keeping this (and me) updated..

Thank you so much!!!!
