### ISSUE TITLE
Downloads are giving error 404 once again

### ISSUE THREAD

**Issue by dirkschut** [i3arnon/YouCast#88]
Since about 6-8 hours ago, downloads from YouCast feeds are giving error 404. Not a quota issue. Perhaps updating YouTube Explode will fix this.

Edit: I'm not currently at a dev machine so I can't test it myself, but there have been a lot of updates to explode since the last YouCast update, so I think this might be the fix.

Edit2: There also appears to be a fork that has some active development called ReExplode.

**Comment by qtlin** [comment]
Many videos still don't download. May be makes sense to try ReExplode?

**Comment by dirkschut** [comment]
Did you try my new version @qtlin ? Because I'm not having any issues with the updated Explode

**Comment by qtlin** [comment]
Upon detailed investigation I discovered that some videos download only if podcast reader co-located with YouCast, e.g. shares the same external IP address.
For example
`curl -vLO 'http://myyoucast:port/Video.mp4?videoId=xxxxxxxxxx&encoding=MP4_720p'`
works from the same IP as YouCast but gets
`HTTP/1.1 403 Forbidden`
from youtube server if ran from elsewhere.
Youtube clearly imposes selective restriction by an unknown IP related criteria.

**Comment by dirkschut** [comment]
@qtlin I'm not having this issue myself... Can you give some video IDs for me to test?

**Comment by maxol18** [comment]
No issue to download with v2.23.1 everything works fine on my side

**Comment by i3arnon** [comment]
New release: https://github.com/i3arnon/YouCast/releases/tag/2.24.0

**Comment by i3arnon** [comment]
> Upon detailed investigation I discovered that some videos download only if podcast reader co-located with YouCast, e.g. shares the same external IP address. For example `curl -vLO 'http://myyoucast:port/Video.mp4?videoId=xxxxxxxxxx&encoding=MP4_720p'` works from the same IP as YouCast but gets `HTTP/1.1 403 Forbidden` from youtube server if ran from elsewhere. Youtube clearly imposes selective restriction by an unknown IP related criteria.

Yes. I gathered that a long time ago which is why I let go of the cloud service.

**Comment by qtlin** [comment]
@i3arnon that is why I mentioned earlier that YouCast should **proxy** connection instead of responding with a URL which includes hardcoded IP address of YouCast system.
A possible workaround is to replace an IP in returned URL with an IP of incoming connection.
