### ISSUE TITLE
build instructions

### ISSUE THREAD

**Issue by qtlin** [i3arnon/YouCast#9]
Dear @i3arnon ,
I attempted to import source into a dev studio and recompile. However there is an Azure cloud service code which is not immediately recognized by dev studio and most likely not used for a stand alone application.
Would you mind providing basic rebuild instructions?
Thanks in advance.

**Comment by i3arnon** [comment]
@qtlin I'm using it to host a YouCast service on Azure that only I use (for now).
I can add some info on what you need to install to make that work, but if you only want to mess around with YouCast you can safely unload that project.

**Comment by qtlin** [comment]
Dear @i3arnon ,
I unloaded that project but build still fails. for example
Error | 5 | Invalid expression term | '' | C:\Users\qtlin\Downloads\YouCast-master\YouCast-master\Source\Service\YoutubeFeed.cs | 258 | 62 | Service
Line 258 reads
userVideo.Title = new TextSyndicationContent($"{i}. {userVideo.Title.Text}");
and many more "Invalid expression terms",  and "Syntax errors".

I am new to .NET and may miss something fundamental, please advise.

**Comment by i3arnon** [comment]
It seems as though you have an old version of Visual Studio that doesn't support C# 6.0, specifically [string interpolation](https://msdn.microsoft.com/en-us/library/dn961160.aspx).

You need to install VS 2015 to compile this code, but if you only want to use YouCast you can download it from http://youcast.i3arnon.com/

**Comment by qtlin** [comment]
Studio 2015 gave errors in WorkerRole.cs
Error	CS0234	The type or namespace name 'ServiceRuntime' does not exist in the namespace 'Microsoft.WindowsAzure' 	5 
and some more after. What more Azure related needs be removed for a standalone application?

**Comment by i3arnon** [comment]
Hey, both the CloudService project and the ServiceWorkerRole project need to be unloaded to get away from the Azure stuff.
