### ISSUE TITLE
Extremely slow downloads, error when finished

### ISSUE THREAD

**Issue by jp-man25** [i3arnon/YouCast#93]
Using Musicbee, the download speed is about 50kbs despite having really fast internet, and most of the time it errors when it's done downloading. 
![image](https://github.com/user-attachments/assets/b1609b2a-6b08-4065-a1bb-0c98b15c8ded)

I've also found when I don't have the episodes downloaded, if I try to advance or go back a few seconds while playing, the app just freezes and I have to restart. Also happens sometimes when I pause and resume.

The video titles are in Japanese, in case that matters.

**Comment by qtlin** [comment]
I am curious, what does Musicbee have to do with YouCast? It is not clear from your message.

**Comment by jp-man25** [comment]
Sorry. I am using Youcast to get an RSS feed for Youtube playlists, and adding them as podcasts in Musicbee.

**Comment by qtlin** [comment]
Audio only mode has never worked properly on some devices. Video is generally works very well, at least in iTunes. Also, you may want to recompile since YoutubeExplode is on 6.4 now while currently compiled in YouCast is 6.3.13.

**Comment by jp-man25** [comment]
I tried video and yeah, it's a LOT faster and I don't get errors, works great. Would still be cool to have audio only working better if possible.

Thank you.
